db.student_info.insertMany([
	{
		s_no: 501,
		student_name: 'Parvati Sallam',
		father_name: 'Narmadaprasad',
		mother_name: 'Seema Bai',
		dob: '5/6/2009',
		caste: 'Gond',
		category: 'ST',
		scholar_no: 495,
		class: '5th',
		medium: 'English',
		gender: 'Female',
		aadhar: '',
		samagra: 115529539,
		ac_no: '',
		address: '',
	},
	{
		s_no: 502,
		student_name: 'Prachi',
		father_name: 'Chandar',
		mother_name: 'Durgo Bai',
		dob: '4/12/2007',
		caste: 'Gond',
		category: 'ST',
		scholar_no: 712,
		class: '5th',
		medium: 'English',
		gender: 'Female',
		aadhar: 360300000000,
		samagra: '',
		ac_no: '',
		address: 'Dawatpura',
	},
	{
		s_no: 503,
		student_name: 'Umesh Devda',
		father_name: 'Chhotelal',
		mother_name: 'Manju Bai',
		dob: '7/5/2010',
		caste: 'Korku',
		category: 'ST',
		scholar_no: 473,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 100884680,
		ac_no: '',
		address: '',
	},
	{
		s_no: 504,
		student_name: 'Alshifa Khan',
		father_name: 'Anish',
		mother_name: 'Afsana',
		dob: '6/9/2008',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 487,
		class: '5th',
		medium: 'English',
		gender: 'Female',
		aadhar: '',
		samagra: 125252648,
		ac_no: '',
		address: '',
	},
	{
		s_no: 505,
		student_name: 'Disha Vishwakarma',
		father_name: 'Suresh',
		mother_name: 'Aruna',
		dob: '24-04-2010',
		caste: 'Khati',
		category: 'OBC',
		scholar_no: 551,
		class: '5th',
		medium: 'English',
		gender: 'Female',
		aadhar: '',
		samagra: 114261547,
		ac_no: '',
		address: '',
	},
	{
		s_no: 506,
		student_name: 'Aliya Khan',
		father_name: 'Irfan',
		mother_name: 'Rukhsana',
		dob: '3/9/2008',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 990,
		class: '5th',
		medium: 'English',
		gender: 'Female',
		aadhar: 755811000000,
		samagra: 193191719,
		ac_no: '',
		address: '',
	},
	{
		s_no: 507,
		student_name: 'Toshib Khan',
		father_name: 'Shakur',
		mother_name: 'Tarun Bee',
		dob: '6/6/2007',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 539,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: 565398000000,
		samagra: 100858221,
		ac_no: '',
		address: '',
	},
	{
		s_no: 508,
		student_name: 'Rihan Khan',
		father_name: 'Anwar',
		mother_name: 'Farida Bee',
		dob: '9/5/2009',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 480,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 509,
		student_name: 'Aavesh Khan',
		father_name: 'Anish',
		mother_name: 'Afsana',
		dob: '12/1/2010',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 485,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: 746135000000,
		samagra: 125253257,
		ac_no: '',
		address: '',
	},
	{
		s_no: 510,
		student_name: 'Anvesh Khan',
		father_name: 'Asgar',
		mother_name: 'Sahiba',
		dob: '12/7/2009',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 486,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: 332290000000,
		samagra: 124083776,
		ac_no: '',
		address: '',
	},
	{
		s_no: 511,
		student_name: 'Usman Khan',
		father_name: 'Hanif',
		mother_name: 'Anisha',
		dob: '1/1/2008',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 461,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 127495019,
		ac_no: '',
		address: '',
	},
	{
		s_no: 512,
		student_name: 'Salman Khan',
		father_name: 'Azad',
		mother_name: 'Samina',
		dob: '30-04-2009',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 496,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 127505955,
		ac_no: '',
		address: '',
	},
	{
		s_no: 513,
		student_name: 'Shahib Khan',
		father_name: 'Iqbal',
		mother_name: 'Rukhsana',
		dob: '20-04-2009',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 991,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 122865625,
		ac_no: '',
		address: 'Kothda',
	},
	{
		s_no: 514,
		student_name: 'Ayush Rathore',
		father_name: 'Rajesh',
		mother_name: 'Pinki',
		dob: '29-06-2010',
		caste: 'Teli',
		category: 'OBC',
		scholar_no: 555,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 128583753,
		ac_no: '',
		address: '',
	},
	{
		s_no: 515,
		student_name: 'Shahil Khan',
		father_name: 'Jahid',
		mother_name: 'Shanu Bee',
		dob: '8/5/2010',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: '',
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 122990607,
		ac_no: '',
		address: 'Kothda',
	},
	{
		s_no: 516,
		student_name: 'Vaseem Khan',
		father_name: 'Safiq',
		mother_name: 'Rubina',
		dob: '2/2/2007',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 619,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 123847038,
		ac_no: '',
		address: '',
	},
	{
		s_no: 517,
		student_name: 'Shahil Khan',
		father_name: 'Jahid',
		mother_name: 'Mehraj',
		dob: '28-08-2007',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: '',
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: 'Kothda',
	},
	{
		s_no: 518,
		student_name: 'Vaseem Khan',
		father_name: 'Inus',
		mother_name: 'Shanu Bee',
		dob: '12/10/2009',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 664,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 100146292,
		ac_no: '',
		address: '',
	},
	{
		s_no: 519,
		student_name: 'Tarun Soner',
		father_name: 'Santosh',
		mother_name: 'Namrita',
		dob: '30-12-2010',
		caste: 'Navda',
		category: 'OBC',
		scholar_no: 474,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: 710417000000,
		samagra: 114336782,
		ac_no: '',
		address: '',
	},
	{
		s_no: 520,
		student_name: 'Sumit Vishwakarma',
		father_name: 'Vishnu',
		mother_name: 'Vimla Bai',
		dob: '7/7/2009',
		caste: 'Khati',
		category: 'OBC',
		scholar_no: 476,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: 742133000000,
		samagra: 100416453,
		ac_no: '',
		address: '',
	},
	{
		s_no: 521,
		student_name: 'Vikky Tanwar',
		father_name: 'Narmadaprasad',
		mother_name: 'Dipti',
		dob: '17-09-2010',
		caste: 'Tanwar',
		category: 'OBC',
		scholar_no: 992,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 123032532,
		ac_no: '',
		address: '',
	},
	{
		s_no: 522,
		student_name: 'Shoheb Khan',
		father_name: 'Tayyab',
		mother_name: 'Noushad',
		dob: '8/8/2009',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 717,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: 526381000000,
		samagra: 195789176,
		ac_no: '',
		address: 'Ambada',
	},
	{
		s_no: 523,
		student_name: 'Jishan Khan',
		father_name: 'Irshad',
		mother_name: 'Bhuri Bee',
		dob: '28-11-2010',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 756,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 129386699,
		ac_no: '',
		address: 'Neemkheda',
	},
	{
		s_no: 524,
		student_name: 'Vaseem Khan',
		father_name: 'Hameed',
		mother_name: 'Baskar',
		dob: '20-08-2007',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 745,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 123898555,
		ac_no: '',
		address: 'Kothda',
	},
	{
		s_no: 525,
		student_name: 'Jubair Khan',
		father_name: 'Vahid',
		mother_name: 'Sabila',
		dob: '27-09-2007',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 744,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: 'Neemkheda',
	},
	{
		s_no: 526,
		student_name: 'Najiya Khan',
		father_name: 'Chhotu',
		mother_name: 'Sehnaz',
		dob: '25-07-2008',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 728,
		class: '5th',
		medium: 'English',
		gender: 'Female',
		aadhar: 8959510120,
		samagra: 100137333,
		ac_no: '',
		address: 'Kharpa',
	},
	{
		s_no: 527,
		student_name: 'Tahira Khan',
		father_name: 'Rahish',
		mother_name: 'Bano Bee',
		dob: '6/8/2009',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 742,
		class: '5th',
		medium: 'English',
		gender: 'Female',
		aadhar: '',
		samagra: 122124083,
		ac_no: '',
		address: 'Kothda',
	},
	{
		s_no: 528,
		student_name: 'Kajal Kaneriya',
		father_name: 'Lakhan',
		mother_name: 'Sunita',
		dob: '8/9/2010',
		caste: 'Balai',
		category: 'SC',
		scholar_no: 712,
		class: '5th',
		medium: 'English',
		gender: 'Female',
		aadhar: 360300000000,
		samagra: 100884447,
		ac_no: '',
		address: 'Dawatpura',
	},
	{
		s_no: 529,
		student_name: 'Tahir Khan',
		father_name: 'Vahid',
		mother_name: 'Haseena',
		dob: '10/5/2002',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 894,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: 'Kothda',
	},
	{
		s_no: 530,
		student_name: 'Sahil Khan',
		father_name: 'Sher Khan',
		mother_name: 'Aruna',
		dob: '15-02-2003',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 926,
		class: '5th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 111035970,
		ac_no: '',
		address: 'Ambada',
	},
	{
		s_no: 531,
		student_name: 'Ashifa Khan',
		father_name: 'Tayyab',
		mother_name: 'Noushad Bee',
		dob: '10/11/2010',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 985,
		class: '5th',
		medium: 'English',
		gender: 'Female',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 532,
		student_name: 'Renuka',
		father_name: 'Mansaram',
		mother_name: 'Shobha',
		dob: '15-01-2010',
		caste: '',
		category: 'SC',
		scholar_no: 926,
		class: '5th',
		medium: 'English',
		gender: '',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 533,
		student_name: 'Juber Khan',
		father_name: 'Rahmat',
		mother_name: 'Rani Bee',
		dob: '',
		caste: '',
		category: 'OBC',
		scholar_no: '',
		class: '5th',
		medium: 'English',
		gender: '',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 601,
		student_name: 'Bhumika Rathore',
		father_name: 'Narmadaprasad',
		mother_name: 'Basanti',
		dob: '28-10-2006',
		caste: 'Balai',
		category: 'SC',
		scholar_no: 614,
		class: '6th',
		medium: 'English',
		gender: 'Female',
		aadhar: 827013000000,
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 602,
		student_name: 'Sakshi Solanki',
		father_name: 'Sujan',
		mother_name: 'Kala Bai',
		dob: '6/8/2010',
		caste: 'Navda',
		category: 'OBC',
		scholar_no: 372,
		class: '6th',
		medium: 'English',
		gender: 'Female',
		aadhar: 497653000000,
		samagra: 114323742,
		ac_no: '',
		address: '',
	},
	{
		s_no: 603,
		student_name: 'Najmeen Khan',
		father_name: 'Rajak',
		mother_name: 'Jayda Bee',
		dob: '4/4/2008',
		caste: 'Fakir',
		category: 'OBC',
		scholar_no: 336,
		class: '6th',
		medium: 'English',
		gender: 'Female',
		aadhar: 828768000000,
		samagra: 123935362,
		ac_no: '',
		address: '',
	},
	{
		s_no: 604,
		student_name: 'Mahak Chouhan',
		father_name: 'Nandram',
		mother_name: 'Barkha',
		dob: '6/8/2010',
		caste: 'Navda',
		category: 'OBC',
		scholar_no: 367,
		class: '6th',
		medium: 'English',
		gender: 'Female',
		aadhar: 730149000000,
		samagra: 114334457,
		ac_no: '',
		address: '',
	},
	{
		s_no: 605,
		student_name: 'Nikita Chouhan',
		father_name: 'Sitaram',
		mother_name: 'Mamta Bai',
		dob: '3/8/2010',
		caste: 'Navda',
		category: 'OBC',
		scholar_no: 371,
		class: '6th',
		medium: 'English',
		gender: 'Female',
		aadhar: 844915000000,
		samagra: 116050937,
		ac_no: '',
		address: '',
	},
	{
		s_no: 606,
		student_name: 'Shivani Solanki',
		father_name: 'Rambharos',
		mother_name: 'Rekha Bai',
		dob: '3/7/2010',
		caste: 'Navda',
		category: 'OBC',
		scholar_no: 382,
		class: '6th',
		medium: 'English',
		gender: 'Female',
		aadhar: '',
		samagra: 115459754,
		ac_no: '',
		address: '',
	},
	{
		s_no: 607,
		student_name: 'Ritika Solanki',
		father_name: 'Sujan',
		mother_name: 'Kala Bai',
		dob: '7/11/2009',
		caste: 'Navda',
		category: 'OBC',
		scholar_no: 373,
		class: '6th',
		medium: 'English',
		gender: 'Female',
		aadhar: 497653000000,
		samagra: 114324417,
		ac_no: '',
		address: '',
	},
	{
		s_no: 608,
		student_name: 'Nargish Khan',
		father_name: 'Shahid',
		mother_name: 'Bhuri Bee',
		dob: '14-06-2006',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 517,
		class: '6th',
		medium: 'English',
		gender: 'Female',
		aadhar: 912890000000,
		samagra: 121918430,
		ac_no: '',
		address: '',
	},
	{
		s_no: 609,
		student_name: 'Rihan Khan',
		father_name: 'Bhuru',
		mother_name: 'Rubina Bee',
		dob: '13-04-2009',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 267,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 100152453,
		ac_no: '',
		address: 'Neemkheda',
	},
	{
		s_no: 610,
		student_name: 'Ameen Khan',
		father_name: 'Sher Kha',
		mother_name: 'Samina Bee',
		dob: '2/2/2006',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 443,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: 725199000000,
		samagra: 129322001,
		ac_no: '',
		address: '',
	},
	{
		s_no: 611,
		student_name: 'Anas Khan',
		father_name: 'Vahid',
		mother_name: 'Sabeena Bee',
		dob: '5/7/2010',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 344,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: 812685000000,
		samagra: 100859199,
		ac_no: '',
		address: '',
	},
	{
		s_no: 612,
		student_name: 'Sohel Khan',
		father_name: 'Habib',
		mother_name: 'Bano Bee',
		dob: '16-07-2008',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 348,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: 496586000000,
		samagra: 305919162,
		ac_no: '',
		address: '',
	},
	{
		s_no: 613,
		student_name: 'Shan Khan',
		father_name: 'Sadik',
		mother_name: 'Jubeda Bee',
		dob: '16-01-2009',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 594,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 124607636,
		ac_no: '',
		address: '',
	},
	{
		s_no: 614,
		student_name: 'Shabir Khan',
		father_name: 'Ramjan',
		mother_name: 'Nagina Bee',
		dob: '17-06-2008',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 672,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: 764046000000,
		samagra: 100857311,
		ac_no: '',
		address: 'Ambada',
	},
	{
		s_no: 615,
		student_name: 'Faijan Khan',
		father_name: 'Hanif',
		mother_name: 'Taslim',
		dob: '5/4/2007',
		caste: 'Fakir',
		category: 'OBC',
		scholar_no: 530,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 126369550,
		ac_no: '',
		address: '',
	},
	{
		s_no: 616,
		student_name: 'Ayaan Khan',
		father_name: 'Ayyub',
		mother_name: 'Mehraj',
		dob: '9/3/2007',
		caste: 'Luhar',
		category: 'OBC',
		scholar_no: 608,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 127244558,
		ac_no: '',
		address: '',
	},
	{
		s_no: 617,
		student_name: 'Yusuf Khan',
		father_name: 'Latif',
		mother_name: 'Baskar',
		dob: '15-05-2008',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 613,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 100770005,
		ac_no: '',
		address: '',
	},
	{
		s_no: 618,
		student_name: 'Moushin Khan',
		father_name: 'Rafik',
		mother_name: 'Jarina',
		dob: '8/6/2008',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: '',
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: 228533000000,
		samagra: 26189752,
		ac_no: '',
		address: '',
	},
	{
		s_no: 619,
		student_name: 'Jamil Khan',
		father_name: 'Yunus',
		mother_name: 'Shanu Bee',
		dob: '15-02-2008',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 662,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 700146238,
		ac_no: '',
		address: '',
	},
	{
		s_no: 620,
		student_name: 'Shakil Khan',
		father_name: 'Yunus',
		mother_name: 'Shanu Bee',
		dob: '4/5/2008',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 663,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 100146176,
		ac_no: '',
		address: '',
	},
	{
		s_no: 621,
		student_name: 'Raja Khan',
		father_name: 'Iqbal',
		mother_name: 'Rubina',
		dob: '20-02-2008',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 623,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 100774596,
		ac_no: '',
		address: '',
	},
	{
		s_no: 622,
		student_name: 'Ashfaq Khan',
		father_name: 'Rahish',
		mother_name: 'Shana',
		dob: '8/9/2008',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 328,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: 284752000000,
		samagra: 100858434,
		ac_no: '',
		address: '',
	},
	{
		s_no: 623,
		student_name: 'Jubair Khan',
		father_name: 'Farukh',
		mother_name: 'Tarjuman',
		dob: '18-03-2009',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 767,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 129395955,
		ac_no: '',
		address: '',
	},
	{
		s_no: 624,
		student_name: 'Nargish Khan',
		father_name: 'Firoj',
		mother_name: 'Nafisha',
		dob: '11/12/2008',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 620,
		class: '6th',
		medium: 'English',
		gender: 'Female',
		aadhar: '',
		samagra: 121918430,
		ac_no: '',
		address: '',
	},
	{
		s_no: 625,
		student_name: 'Devesh Chouhan',
		father_name: 'Kamlesh',
		mother_name: 'Vijaylaxmi',
		dob: '12/8/2010',
		caste: 'Navda',
		category: 'OBC',
		scholar_no: 490,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 114395981,
		ac_no: '',
		address: '',
	},
	{
		s_no: 626,
		student_name: 'Soyab Khan',
		father_name: 'Mubarik',
		mother_name: 'Chanda Bee',
		dob: '6/6/2008',
		caste: '',
		category: 'OBC',
		scholar_no: 1000,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 627,
		student_name: 'Shine Khan',
		father_name: 'Anish',
		mother_name: 'Samina Bee',
		dob: '10/2/2004',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 922,
		class: '6th',
		medium: 'English',
		gender: 'Female',
		aadhar: '34006548/723',
		samagra: 126094264,
		ac_no: '',
		address: 'Neemkheda',
	},
	{
		s_no: 628,
		student_name: 'Rihan Khan',
		father_name: 'Anwar',
		mother_name: 'Farida',
		dob: '9/5/2009',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 916,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: 701722000000,
		samagra: 114319233,
		ac_no: '',
		address: 'Gadiya',
	},
	{
		s_no: 629,
		student_name: 'Ajay Rathore',
		father_name: 'Mohan',
		mother_name: 'Bhagwati',
		dob: '12/9/2006',
		caste: 'Balai',
		category: 'SC',
		scholar_no: 970,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: 'Kothda',
	},
	{
		s_no: 630,
		student_name: 'Yusuf Khan',
		father_name: 'Hanif',
		mother_name: 'Syanu',
		dob: '21-08-2007',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 978,
		class: '6th',
		medium: 'English',
		gender: 'Male',
		aadhar: 76771497976,
		samagra: 115403825,
		ac_no: '',
		address: '',
	},
	{
		s_no: 631,
		student_name: 'Aafrin Khan',
		father_name: 'Aashik',
		mother_name: 'Taj Bee',
		dob: '',
		caste: '',
		category: 'OBC',
		scholar_no: '',
		class: '6th',
		medium: 'English',
		gender: '',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 632,
		student_name: 'Aashik Khan',
		father_name: 'Habib',
		mother_name: 'Baskar',
		dob: '8/4/2007',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: '',
		class: '6th',
		medium: 'English',
		gender: '',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 633,
		student_name: 'Aaliya Khan',
		father_name: 'Umarkha',
		mother_name: 'Baskar',
		dob: '27-05-2007',
		caste: '',
		category: 'OBC',
		scholar_no: 911,
		class: '6th',
		medium: 'English',
		gender: '',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 634,
		student_name: 'Anjali Rathore',
		father_name: 'Narmadaprasad',
		mother_name: 'Basanti',
		dob: '2/8/2007',
		caste: 'Rathore',
		category: 'SC',
		scholar_no: 1005,
		class: '6th',
		medium: 'English',
		gender: '',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 635,
		student_name: 'Sonam',
		father_name: 'Mukesh',
		mother_name: 'Manisha',
		dob: '1/1/2005',
		caste: 'Korku',
		category: 'ST',
		scholar_no: 469,
		class: '6th',
		medium: 'English',
		gender: '',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 636,
		student_name: 'Karan Rathore',
		father_name: 'Narmadaprasad',
		mother_name: 'Sunita',
		dob: '1/5/2006',
		caste: 'Teli',
		category: 'OBC',
		scholar_no: 155,
		class: '6th',
		medium: 'English',
		gender: '',
		aadhar: '',
		samagra: 126337840,
		ac_no: '',
		address: '',
	},
	{
		s_no: 637,
		student_name: 'Jamil Khan',
		father_name: '',
		mother_name: '',
		dob: '',
		caste: '',
		category: 'OBC',
		scholar_no: '',
		class: '6th',
		medium: 'English',
		gender: '',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 638,
		student_name: 'Shakil Khan',
		father_name: '',
		mother_name: '',
		dob: '',
		caste: '',
		category: 'OBC',
		scholar_no: '',
		class: '6th',
		medium: 'English',
		gender: '',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 701,
		student_name: 'Sakshi Rathore',
		father_name: 'Manohar',
		mother_name: 'Seema',
		dob: '5/2/2010',
		caste: 'Balai',
		category: 'SC',
		scholar_no: 368,
		class: '7th',
		medium: 'English',
		gender: 'Female',
		aadhar: 52504226403,
		samagra: 20180346,
		ac_no: 34751941859,
		address: '',
	},
	{
		s_no: 702,
		student_name: 'Preeti Kumre',
		father_name: 'Shishupal',
		mother_name: 'Anita Bai',
		dob: '4/1/2004',
		caste: 'Gond',
		category: 'ST',
		scholar_no: 751,
		class: '7th',
		medium: 'English',
		gender: 'Female',
		aadhar: 266223000000,
		samagra: 185517712,
		ac_no: 891618000000000,
		address: '',
	},
	{
		s_no: 703,
		student_name: 'Abhishek',
		father_name: 'Rambaksh',
		mother_name: 'Sharda',
		dob: '11/2/2006',
		caste: 'Balai',
		category: 'SC',
		scholar_no: 529,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 827736000000,
		samagra: 100757589,
		ac_no: 891618000000000,
		address: '',
	},
	{
		s_no: 704,
		student_name: 'Praveen',
		father_name: 'Banapsingh',
		mother_name: 'Kshipra',
		dob: '5/2/2007',
		caste: 'Gond',
		category: 'ST',
		scholar_no: 772,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 225754000000,
		samagra: '',
		ac_no: 12911000000000,
		address: '',
	},
	{
		s_no: 705,
		student_name: 'Nagesh',
		father_name: 'Banapsingh',
		mother_name: 'Kshipra',
		dob: '20-08-2004',
		caste: 'Gond',
		category: 'ST',
		scholar_no: 768,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 145813385,
		ac_no: 12911000000000,
		address: '',
	},
	{
		s_no: 706,
		student_name: 'Sneha Rathore',
		father_name: 'Hariom',
		mother_name: 'Jyoti',
		dob: '9/3/2008',
		caste: 'Teli',
		category: 'OBC',
		scholar_no: 354,
		class: '7th',
		medium: 'English',
		gender: 'Female',
		aadhar: 227698000000,
		samagra: 12857597,
		ac_no: 891610000000000,
		address: '',
	},
	{
		s_no: 707,
		student_name: 'Ashi Solanki',
		father_name: 'Santosh',
		mother_name: 'Sanju Bai',
		dob: '26-05-2008',
		caste: 'Mali',
		category: 'OBC',
		scholar_no: 432,
		class: '7th',
		medium: 'English',
		gender: 'Female',
		aadhar: 413057000000,
		samagra: 100134681,
		ac_no: 891618000000000,
		address: '',
	},
	{
		s_no: 708,
		student_name: 'Sonika Tanwar',
		father_name: 'Rajesh',
		mother_name: 'Sunita',
		dob: '8/5/2008',
		caste: 'Loda',
		category: 'OBC',
		scholar_no: 198,
		class: '7th',
		medium: 'English',
		gender: 'Female',
		aadhar: 825632000000,
		samagra: 12480631,
		ac_no: 891618000000000,
		address: '',
	},
	{
		s_no: 709,
		student_name: 'Ikra Khan',
		father_name: 'Akbar',
		mother_name: 'Parveen',
		dob: '8/5/2007',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: '',
		class: '7th',
		medium: 'English',
		gender: 'Female',
		aadhar: '',
		samagra: 122859539,
		ac_no: '',
		address: '',
	},
	{
		s_no: 710,
		student_name: 'Samreen Khan',
		father_name: 'Shakil',
		mother_name: 'Najma',
		dob: '10/4/2008',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 340,
		class: '7th',
		medium: 'English',
		gender: 'Female',
		aadhar: 282595000000,
		samagra: 123942299,
		ac_no: 891610000000000,
		address: '',
	},
	{
		s_no: 711,
		student_name: 'Simran Khan',
		father_name: 'Enaat',
		mother_name: 'Rihana',
		dob: '2/1/2006',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 771,
		class: '7th',
		medium: 'English',
		gender: 'Female',
		aadhar: 88704008039,
		samagra: 126118975,
		ac_no: 891611000000000,
		address: '',
	},
	{
		s_no: 712,
		student_name: 'Aadil Khan',
		father_name: 'Ayyub',
		mother_name: 'Sajjo Bee',
		dob: '10/2/2007',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 393,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 216012000000,
		samagra: 100858843,
		ac_no: '',
		address: '',
	},
	{
		s_no: 713,
		student_name: 'Afroj Khan',
		father_name: 'Makbul',
		mother_name: 'Ruksana',
		dob: '21-02-2009',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 324,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 100938190,
		ac_no: '',
		address: '',
	},
	{
		s_no: 714,
		student_name: 'Arman Khan',
		father_name: 'Ramjan',
		mother_name: 'Nagina',
		dob: '4/2/2006',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 329,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 761907000000,
		samagra: 100857426,
		ac_no: '',
		address: '',
	},
	{
		s_no: 715,
		student_name: 'Salman Khan',
		father_name: 'Ramjan',
		mother_name: 'Nagina',
		dob: '2/6/2005',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 330,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 309666000000,
		samagra: 100857387,
		ac_no: '',
		address: '',
	},
	{
		s_no: 716,
		student_name: 'Vaseem Khan',
		father_name: 'Safed Kha',
		mother_name: 'Rubeena',
		dob: '8/7/2007',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 342,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 827668000000,
		samagra: 100013523,
		ac_no: '',
		address: '',
	},
	{
		s_no: 717,
		student_name: 'Salman Khan',
		father_name: 'Shabir',
		mother_name: 'Haseena',
		dob: '7/3/2009',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 228,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 247530000000,
		samagra: 100834637,
		ac_no: 891610000000000,
		address: '',
	},
	{
		s_no: 718,
		student_name: 'Arman Khan',
		father_name: 'Shabbir',
		mother_name: 'Sameena',
		dob: '7/6/2008',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 282,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 100835900,
		ac_no: 35394716978,
		address: '',
	},
	{
		s_no: 719,
		student_name: 'Shahrukh Khan',
		father_name: 'Ramjan',
		mother_name: 'Maluki',
		dob: '10/7/2007',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 492,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 690950000000,
		samagra: 114338658,
		ac_no: 891618000000000,
		address: '',
	},
	{
		s_no: 720,
		student_name: 'Rihan Khan',
		father_name: 'Bhura Kha',
		mother_name: 'Lakhu Bee',
		dob: '2/2/2007',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 521,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 642110000000,
		samagra: 20180346,
		ac_no: 891618000000000,
		address: '',
	},
	{
		s_no: 721,
		student_name: 'Arman Khan',
		father_name: 'Anwar',
		mother_name: 'Salma',
		dob: '6/6/2007',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 532,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 966438000000,
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 722,
		student_name: 'Moin Khan',
		father_name: 'Habib',
		mother_name: 'Bano',
		dob: '9/3/2007',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 386,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 704188000000,
		samagra: 305919161,
		ac_no: '',
		address: '',
	},
	{
		s_no: 723,
		student_name: 'Lokesh Khan',
		father_name: 'Narayan',
		mother_name: 'Bhuri Bai',
		dob: '6/6/2006',
		caste: 'Loda',
		category: 'OBC',
		scholar_no: 675,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 513297000000,
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 724,
		student_name: 'Akhlesh Khan',
		father_name: 'Narayan',
		mother_name: 'Bhuri Bai',
		dob: '2/8/2008',
		caste: 'Loda',
		category: 'OBC',
		scholar_no: 674,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 345070000000,
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 725,
		student_name: 'Prateek Binjwa',
		father_name: 'Deepak',
		mother_name: 'Gayatri Bai',
		dob: '13-06-2007',
		caste: 'Mali',
		category: 'OBC',
		scholar_no: 332,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 496198000000,
		samagra: 176808228,
		ac_no: 891618000000000,
		address: '',
	},
	{
		s_no: 726,
		student_name: 'Ayush Raiwal',
		father_name: 'Nandkishore',
		mother_name: 'Vinita Bai',
		dob: '25-08-2009',
		caste: 'Mali',
		category: 'OBC',
		scholar_no: 250,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 546431000000,
		samagra: 100127812,
		ac_no: 891611000000000,
		address: '',
	},
	{
		s_no: 727,
		student_name: 'Goutam Raiwal',
		father_name: 'Govind',
		mother_name: 'Manu Bai',
		dob: '8/7/2007',
		caste: 'Mali',
		category: 'OBC',
		scholar_no: 264,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 100130512,
		ac_no: '',
		address: '',
	},
	{
		s_no: 728,
		student_name: 'Samreen Khan',
		father_name: 'Mustaq',
		mother_name: 'Parveen Bee',
		dob: '5/6/2008',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 759,
		class: '7th',
		medium: 'English',
		gender: 'Female',
		aadhar: 331632000000,
		samagra: 126269289,
		ac_no: 991610000000000,
		address: '',
	},
	{
		s_no: 729,
		student_name: 'Yuvraj Chouhan',
		father_name: 'Dileep',
		mother_name: 'Baskar Bai',
		dob: '10/3/2007',
		caste: 'Navda',
		category: 'OBC',
		scholar_no: 279,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 114391588,
		ac_no: '',
		address: '',
	},
	{
		s_no: 730,
		student_name: 'Sumit Devda',
		father_name: 'Anarsingh',
		mother_name: 'Mamta Bai',
		dob: '9/7/2008',
		caste: 'Korku',
		category: 'ST',
		scholar_no: 1002,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 795753000000,
		samagra: 100868975,
		ac_no: 12910400000000,
		address: '',
	},
	{
		s_no: 731,
		student_name: 'Farman Khan',
		father_name: 'Shabbir',
		mother_name: 'Sameena Bee',
		dob: '6/4/2009',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 281,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: '',
		samagra: 100835993,
		ac_no: '',
		address: '',
	},
	{
		s_no: 732,
		student_name: 'Jyoti Devda',
		father_name: 'Radheshyam',
		mother_name: 'Kshama Bai',
		dob: '3/8/2009',
		caste: 'Korku',
		category: 'ST',
		scholar_no: 454,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 995742000000,
		samagra: 100865937,
		ac_no: '',
		address: '',
	},
	{
		s_no: 733,
		student_name: 'Neema Devda',
		father_name: 'Radheshyam',
		mother_name: 'Kshama Bai',
		dob: '17-02-2007',
		caste: '',
		category: 'ST',
		scholar_no: 455,
		class: '7th',
		medium: 'English',
		gender: 'Male',
		aadhar: 301681000000,
		samagra: 100866075,
		ac_no: '',
		address: '',
	},
	{
		s_no: 801,
		student_name: 'Brijesh Kadole',
		father_name: 'Omprakash',
		mother_name: 'Rambharosi',
		dob: '6/8/2006',
		caste: 'Balai',
		category: 'SC',
		scholar_no: 319,
		class: '8th',
		medium: 'Hindi',
		gender: 'Male',
		aadhar: 542543000000,
		samagra: 100878176,
		ac_no: 12910100000000,
		address: '',
	},
	{
		s_no: 802,
		student_name: 'Roshni Devda',
		father_name: 'Chhotelal',
		mother_name: 'Manju Bai',
		dob: '10/3/2007',
		caste: 'Korku',
		category: 'ST',
		scholar_no: 1004,
		class: '8th',
		medium: 'Hindi',
		gender: 'Female',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 803,
		student_name: 'Bindiya Devda',
		father_name: 'Fulsingh',
		mother_name: 'Sita Bai',
		dob: '12/1/2006',
		caste: 'Korku',
		category: 'ST',
		scholar_no: 538,
		class: '8th',
		medium: 'Hindi',
		gender: 'Female',
		aadhar: 925012000000,
		samagra: 100867416,
		ac_no: 12910100000000,
		address: '',
	},
	{
		s_no: 804,
		student_name: 'Nisha',
		father_name: 'Narmadaprasad',
		mother_name: 'Kshama Bai',
		dob: '31-08-2007',
		caste: 'Korku',
		category: 'ST',
		scholar_no: 607,
		class: '8th',
		medium: 'Hindi',
		gender: 'Female',
		aadhar: '',
		samagra: 14261375,
		ac_no: '',
		address: '',
	},
	{
		s_no: 805,
		student_name: 'Arun',
		father_name: 'Bhurasingh',
		mother_name: 'Ramwati Bai',
		dob: '2/10/2005',
		caste: 'Korku',
		category: 'ST',
		scholar_no: 450,
		class: '8th',
		medium: 'Hindi',
		gender: 'Male',
		aadhar: 910817000000,
		samagra: 100879994,
		ac_no: 12911000000000,
		address: '',
	},
	{
		s_no: 806,
		student_name: 'Sandeep Kakodiya',
		father_name: 'Gokul',
		mother_name: 'Sunita Bai',
		dob: '18-04-2006',
		caste: 'Korku',
		category: 'ST',
		scholar_no: 444,
		class: '8th',
		medium: 'Hindi',
		gender: 'Male',
		aadhar: 785492000000,
		samagra: 177077423,
		ac_no: 12910100000000,
		address: '',
	},
	{
		s_no: 807,
		student_name: 'Soni Rathore',
		father_name: 'Brijesh',
		mother_name: 'Narmadi Bai',
		dob: '6/2/2006',
		caste: 'Teli',
		category: 'OBC',
		scholar_no: 148,
		class: '8th',
		medium: 'Hindi',
		gender: 'Female',
		aadhar: 729809000000,
		samagra: 126418062,
		ac_no: 891610000000000,
		address: '',
	},
	{
		s_no: 808,
		student_name: 'Saloni Raiwal',
		father_name: 'Ramnivas',
		mother_name: 'Mamta Bai',
		dob: '2/2/2007',
		caste: 'Mali',
		category: 'OBC',
		scholar_no: 216,
		class: '8th',
		medium: 'Hindi',
		gender: 'Female',
		aadhar: 555552000000,
		samagra: 100127481,
		ac_no: 891618000000000,
		address: '',
	},
	{
		s_no: 809,
		student_name: 'Nasreen Khan',
		father_name: 'Mustkim',
		mother_name: 'Shahjad Bee',
		dob: '9/1/2007',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 599,
		class: '8th',
		medium: 'Hindi',
		gender: 'Female',
		aadhar: 853695000000,
		samagra: 191116580,
		ac_no: 891675000000000,
		address: '',
	},
	{
		s_no: 810,
		student_name: 'Fija Khan',
		father_name: 'Hakim',
		mother_name: 'Chhanno Bee',
		dob: '27-08-2006',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: '',
		class: '8th',
		medium: 'Hindi',
		gender: 'Female',
		aadhar: 834300000000,
		samagra: 301332193,
		ac_no: '',
		address: '',
	},
	{
		s_no: 811,
		student_name: 'Haseena Khan',
		father_name: 'Iliyas',
		mother_name: 'Bilkis',
		dob: '4/6/2007',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 600,
		class: '8th',
		medium: 'Hindi',
		gender: 'Female',
		aadhar: '',
		samagra: 127168459,
		ac_no: '',
		address: '',
	},
	{
		s_no: 812,
		student_name: 'Salman Khan',
		father_name: 'Shahid',
		mother_name: 'Sameena',
		dob: '11/12/2005',
		caste: 'Fakir',
		category: 'OBC',
		scholar_no: 423,
		class: '8th',
		medium: 'Hindi',
		gender: 'Male',
		aadhar: 756262000000,
		samagra: 100856625,
		ac_no: 891618000000000,
		address: '',
	},
	{
		s_no: 813,
		student_name: 'Ramjan Khan',
		father_name: 'Raje Kha',
		mother_name: 'Mehrun',
		dob: '22-03-2005',
		caste: 'Fakir',
		category: 'OBC',
		scholar_no: 518,
		class: '8th',
		medium: 'Hindi',
		gender: 'Male',
		aadhar: 314615000000,
		samagra: 127151912,
		ac_no: 891610000000000,
		address: '',
	},
	{
		s_no: 814,
		student_name: 'Araslan Khan',
		father_name: 'Bhuru',
		mother_name: 'Rubeena',
		dob: '9/4/2007',
		caste: 'Pindara',
		category: 'OBC',
		scholar_no: 268,
		class: '8th',
		medium: 'Hindi',
		gender: 'Male',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 815,
		student_name: 'Juned Khan',
		father_name: 'Rahish',
		mother_name: 'Rubeena',
		dob: '18-03-2005',
		caste: 'Luhar',
		category: 'OBC',
		scholar_no: 625,
		class: '8th',
		medium: 'Hindi',
		gender: 'Male',
		aadhar: 805979000000,
		samagra: 169466353,
		ac_no: '',
		address: '',
	},
	{
		s_no: 816,
		student_name: 'Banti Binjwa',
		father_name: 'Gayatri',
		mother_name: 'Deepak',
		dob: '3/3/2005',
		caste: 'Mali',
		category: 'OBC',
		scholar_no: 601,
		class: '8th',
		medium: 'Hindi',
		gender: 'Male',
		aadhar: 978550000000,
		samagra: 176808024,
		ac_no: 32370471209,
		address: '',
	},
	{
		s_no: 817,
		student_name: 'Ritesh Soner',
		father_name: 'Jaynarayan',
		mother_name: 'Maniya Bai',
		dob: '8/6/2006',
		caste: 'Navda',
		category: 'OBC',
		scholar_no: 603,
		class: '8th',
		medium: 'Hindi',
		gender: 'Male',
		aadhar: 295433000000,
		samagra: 114331343,
		ac_no: 891618000000000,
		address: '',
	},
	{
		s_no: 818,
		student_name: 'Nitesh',
		father_name: 'Sundarlal',
		mother_name: 'Avanti Bai',
		dob: '11/10/2007',
		caste: 'Balai',
		category: 'SC',
		scholar_no: 899,
		class: '8th',
		medium: 'Hindi',
		gender: 'Male',
		aadhar: 798723000000,
		samagra: 176403917,
		ac_no: '',
		address: 'Kothdi',
	},
	{
		s_no: 819,
		student_name: 'Aarti',
		father_name: 'Shankarlal',
		mother_name: 'Manju Bai',
		dob: '7/2/2005',
		caste: 'Kewat',
		category: 'OBC',
		scholar_no: 898,
		class: '8th',
		medium: 'Hindi',
		gender: 'Female',
		aadhar: 452754000000,
		samagra: 182029564,
		ac_no: '',
		address: 'Kothdi',
	},
	{
		s_no: 820,
		student_name: 'Irfan Khan',
		father_name: 'Anwar',
		mother_name: 'Bhuri',
		dob: '8/2/2005',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 896,
		class: '8th',
		medium: 'Hindi',
		gender: 'Male',
		aadhar: 999219000000,
		samagra: 100753383,
		ac_no: '',
		address: 'Ambada',
	},
	{
		s_no: 821,
		student_name: 'Rabiya Khan',
		father_name: 'Anwar',
		mother_name: 'Farida',
		dob: '24-10-2006',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 914,
		class: '8th',
		medium: 'Hindi',
		gender: 'Female',
		aadhar: 914336000000,
		samagra: 114318250,
		ac_no: '',
		address: 'Gadiya',
	},
	{
		s_no: 822,
		student_name: 'Sumaniya',
		father_name: 'Umarkha',
		mother_name: 'Baskar',
		dob: '11/5/2007',
		caste: 'Mewati',
		category: 'OBC',
		scholar_no: 912,
		class: '8th',
		medium: 'Hindi',
		gender: 'Female',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 823,
		student_name: 'Alkesh',
		father_name: 'Bharat',
		mother_name: 'Sunita Bai',
		dob: '12/2/2002',
		caste: 'Korku',
		category: 'ST',
		scholar_no: '',
		class: '8th',
		medium: 'Hindi',
		gender: 'Male',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
	{
		s_no: 824,
		student_name: 'Ronak Soner',
		father_name: 'Santosh',
		mother_name: 'Namrata',
		dob: '28-04-2008',
		caste: 'Navda',
		category: 'OBC',
		scholar_no: 327,
		class: '8th',
		medium: 'Hindi',
		gender: 'Male',
		aadhar: '',
		samagra: '',
		ac_no: '',
		address: '',
	},
]);
